services:
    app:
      build: .
      image: keno:latest
      container_name: keno
      restart: always
      command: fastapi run app/main.py --host=0.0.0.0 --port 5000
      ports:
        - "8044:5000"
      volumes:
        - .:/app
