services:
    app:
      build: .
      image: keno:latest
      container_name: keno
      command: fastapi run app/main.py --host=0.0.0.0 --port 80
      networks:
        - frontend
      labels:
        - traefik.enable=true
        - traefik.http.routers.globe.rule=Host('debbout.info')
        - traefik.http.routers.globe.entrypoint=web
      restart: unless-stopped
      volumes:
        - .:/app
networks:
  frontend:
    external: true
